version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME ./app
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG-$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf 'version: %s\nResources:\n\t-TargetService:\n\t\tType: AWS::ECS::Service\n\t\tProperties:\n\t\tTaskDefinition: arn:aws:ecs:us-east-2:591328757508:task-definition/development-sinatra:22\n' $IMAGE_TAG-$CODEBUILD_RESOLVED_SOURCE_VERSION > AppSpec.yml
artifacts:
  files:
    - AppSpec.yml
