version: '3.7'

services:
  app:
    image: local/raiseme-app
    build:
      context: .
      args:
        DEVELOPMENT: "true"
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./
        target: /app
