# frozen_string_literal: true

ruby '2.6.3'

source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'ddtrace'
gem 'pry'
gem 'puma', '~> 4.3'
gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib'

group :development do
  gem 'rubocop', require: false
end

group :development, :test do
  gem 'awesome_print'
end
